language: php

before_script:
  - composer install --dev --no-interaction

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - php ./vendor/bin/phpunit --colors --configuration="tests/phpunit.xml.dist" --coverage-clover ./tests/clover-zip-archive.xml
  - php ./vendor/bin/coverage-checker.php ./tests/clover-zip-archive.xml 100
  - php ./vendor/bin/phpcs --standard=Rasserbia ./src --ignore=./tests/*